#install.packages("tidyverse")
library(dplyr)
library(stringr)


#read in the CSV file, change the path to where your CSV is located
laserDirection <- read.csv("C:/laser_current.csv", header = TRUE)

laserDirection$laserClockDir <- "na"

#create a field of clock directions of the laser strike from the Remarks column
laserDirection$laserClockDir <- case_when(
  str_detect(laserDirection$remarks, "11-12 o'clock position") ~ "11 to 12 o'clock",  
  str_detect(laserDirection$remarks, "12 o'clock") ~ "12 o'clock",  
  str_detect(laserDirection$remarks, "12O'clock") ~ "12 o'clock",  
  str_detect(laserDirection$remarks, "12o'clock") ~ "12 o'clock", 
  str_detect(laserDirection$remarks, "12 o' clock") ~ "12 o'clock",  
  str_detect(laserDirection$remarks, "12 O'Clock") ~ "12 o'clock",
  str_detect(laserDirection$remarks, "12 oclock") ~ "12 o'clock",
  str_detect(laserDirection$remarks, "12O'Clock") ~ "12 o'clock",
  str_detect(laserDirection$remarks, "12 O' Clock") ~ "12 o'clock",
  str_detect(laserDirection$remarks, "12O' Clock") ~ "12 o'clock",
  str_detect(laserDirection$remarks, "12 O'clock") ~ "12 o'clock",   
  str_detect(laserDirection$remarks, "12 0'clock") ~ "12 o'clock", 
  str_detect(laserDirection$remarks, "12 0'clock") ~ "12 o'clock", 
  str_detect(laserDirection$remarks, "12 O'CLOCK") ~ "12 o'clock", 
  str_detect(laserDirection$remarks, "12 o clock") ~ "12 o'clock", 
  str_detect(laserDirection$remarks, "12 p'clock") ~ "12 o'clock", 
  str_detect(laserDirection$remarks, "twelve o'clock") ~ "12 o'clock",
  str_detect(laserDirection$remarks, "12:00 o'clock") ~ "12 o'clock",
  str_detect(laserDirection$remarks, "12 'clock") ~ "12 o'clock",
  str_detect(laserDirection$remarks, "12'oclock") ~ "12 o'clock",
  str_detect(laserDirection$remarks, "12 o;clock") ~ "12 o'clock",
  str_detect(laserDirection$remarks, "12 o.clock") ~ "12 o'clock",
  str_detect(laserDirection$remarks, "from the 12") ~ "12 o'clock",
  str_detect(laserDirection$remarks, "2 o'clock") ~ "2 o'clock",  
  str_detect(laserDirection$remarks, "2 O'Clock") ~ "2 o'clock",
  str_detect(laserDirection$remarks, "2 O' Clock") ~ "2 o'clock",
  str_detect(laserDirection$remarks, "2O'Clock") ~ "2 o'clock",
  str_detect(laserDirection$remarks, "2 O'clock") ~ "2 o'clock",
  str_detect(laserDirection$remarks, "2O'clock") ~ "2 o'clock",
  str_detect(laserDirection$remarks, "2 O'CLOCK") ~ "2 o'clock",
  str_detect(laserDirection$remarks, "2 0'clock") ~ "2 o'clock",
  str_detect(laserDirection$remarks, "two o'clock") ~ "2 o'clock",
  str_detect(laserDirection$remarks, "2o'clock") ~ "2 o'clock",
  str_detect(laserDirection$remarks, "2 'clock") ~ "2 o'clock",
  str_detect(laserDirection$remarks, "2 'o clock") ~ "2 o'clock",
  str_detect(laserDirection$remarks, "2 oclock") ~ "2 o'clock",
  str_detect(laserDirection$remarks, "2 o;clock") ~ "2 o'clock",
  str_detect(laserDirection$remarks, "2 O'Cock") ~ "2 o'clock",
  str_detect(laserDirection$remarks, "from the 2:30") ~ "2:30 o'clock",
  str_detect(laserDirection$remarks, "from the 2") ~ "2 o'clock",
  TRUE ~ as.character(laserDirection$laserClockDir))

laserDirection$laserClockDir <- case_when(
  str_detect(laserDirection$remarks, "11 o'clock") ~ "11 o'clock", 
  str_detect(laserDirection$remarks, "11O'Clock") ~ "11 o'clock",  
  str_detect(laserDirection$remarks, "11:00 o'clock") ~ "11 o'clock",
  str_detect(laserDirection$remarks, "11 O'Clock") ~ "11 o'clock",  
  str_detect(laserDirection$remarks, "11 O'clock") ~ "11 o'clock",  
  str_detect(laserDirection$remarks, "11O'Clock") ~ "11 o'clock", 
  str_detect(laserDirection$remarks, "11 O' Clock") ~ "11 o'clock", 
  str_detect(laserDirection$remarks, "eleven o'clock") ~ "11 o'clock",
  str_detect(laserDirection$remarks, "11o'clock") ~ "11 o'clock",
  str_detect(laserDirection$remarks, "ElevenO'clock") ~ "11 o'clock",
  str_detect(laserDirection$remarks, "eleven O'clock") ~ "11 o'clock",
  str_detect(laserDirection$remarks, "elevenO'clock") ~ "11 o'clock",
  str_detect(laserDirection$remarks, "11 0'clock") ~ "11 o'clock",
  str_detect(laserDirection$remarks, "1 o'clock") ~ "1 o'clock",  
  str_detect(laserDirection$remarks, "1 oclock") ~ "1 o'clock",
  str_detect(laserDirection$remarks, "1 o;clock") ~ "1 o'clock",
  str_detect(laserDirection$remarks, "1 O'Clock") ~ "1 o'clock",
  str_detect(laserDirection$remarks, "one o'clock") ~ "1 o'clock",
  str_detect(laserDirection$remarks, "oneo'clock") ~ "1 o'clock",
  str_detect(laserDirection$remarks, "1'oclock") ~ "1 o'clock",
  str_detect(laserDirection$remarks, "1 O'clock") ~ "1 o'clock",
  str_detect(laserDirection$remarks, "1 O'CLOCK") ~ "1 o'clock",
  str_detect(laserDirection$remarks, "OneO'clock") ~ "1 o'clock",
  str_detect(laserDirection$remarks, "one O'clock") ~ "1 o'clock",
  str_detect(laserDirection$remarks, "oneO'clock") ~ "1 o'clock",
  str_detect(laserDirection$remarks, "1o'clock") ~ "1 o'clock",
  str_detect(laserDirection$remarks, "One O'clock") ~ "1 o'clock",
  str_detect(laserDirection$remarks, "1 0'clock") ~ "1 o'clock",
  str_detect(laserDirection$remarks, "1 o-clock") ~ "1 o'clock",
  str_detect(laserDirection$remarks, "1:30 O'clock") ~ "1:30 o'clock",
  TRUE ~ as.character(laserDirection$laserClockDir))

laserDirection$laserClockDir <- case_when(
  str_detect(laserDirection$remarks, "2to3O'Clock") ~ "2 to 3 o'clock",
  str_detect(laserDirection$remarks, "1 o'clock to 3 o'clock") ~ "1 to 3 o'clock",
  str_detect(laserDirection$remarks, "3O'Clock") ~ "3 o'clock", 
  str_detect(laserDirection$remarks, "3 o'clock") ~ "3 o'clock",  
  str_detect(laserDirection$remarks, "3 O'Clock") ~ "3 o'clock", 
  str_detect(laserDirection$remarks, "3 OClock") ~ "3 o'clock", 
  str_detect(laserDirection$remarks, "3 oclock") ~ "3 o'clock",
  str_detect(laserDirection$remarks, "3O'clock") ~ "3 o'clock",
  str_detect(laserDirection$remarks, "3 O'clock") ~ "3 o'clock",
  str_detect(laserDirection$remarks, "3o'clock") ~ "3 o'clock",
  str_detect(laserDirection$remarks, "3 O'CLOCK") ~ "3 o'clock",
  str_detect(laserDirection$remarks, "three o'clock") ~ "3 o'clock",
  str_detect(laserDirection$remarks, "3 O' Clock") ~ "3 o'clock",
  str_detect(laserDirection$remarks, "3 o' clock") ~ "3 o'clock",
  str_detect(laserDirection$remarks, "3 0'clock") ~ "3 o'clock",
  str_detect(laserDirection$remarks, "from the 3 position") ~ "3 o'clock",
  str_detect(laserDirection$remarks, "4 o'clock") ~ "4 o'clock",  
  str_detect(laserDirection$remarks, "4 O'Clock") ~ "4 o'clock",  
  str_detect(laserDirection$remarks, "4o'clock") ~ "4 o'clock",
  str_detect(laserDirection$remarks, "4O'Clock") ~ "4 o'clock",
  str_detect(laserDirection$remarks, "4O'clock") ~ "4 o'clock",
  str_detect(laserDirection$remarks, "4 O'clock") ~ "4 o'clock",
  str_detect(laserDirection$remarks, "4 o;clock") ~ "4 o'clock",
  str_detect(laserDirection$remarks, "5 o'clock") ~ "5 o'clock",  
  str_detect(laserDirection$remarks, "5 O'Clock") ~ "5 o'clock",  
  str_detect(laserDirection$remarks, "5 0'clock") ~ "5 o'clock",  
  str_detect(laserDirection$remarks, "5o'clock") ~ "5 o'clock",  
  str_detect(laserDirection$remarks, "five o'clock") ~ "5 o'clock",  
  str_detect(laserDirection$remarks, "2 o'clock to 6 o'clock") ~ "2 to 6 o'clock",
  str_detect(laserDirection$remarks, "12 o'clock to the 6 o'clock") ~ "2 to 6 o'clock",
  str_detect(laserDirection$remarks, "12o'clockthrough6o'clock") ~ "2 to 6 o'clock",
  str_detect(laserDirection$remarks, "6 o'clock") ~ "6 o'clock",
  str_detect(laserDirection$remarks, "6O'clock") ~ "6 o'clock",
  str_detect(laserDirection$remarks, "6 O'Clock") ~ "6 o'clock",
  str_detect(laserDirection$remarks, "6o'clock") ~ "6 o'clock",
  str_detect(laserDirection$remarks, "6 O'clock") ~ "6 o'clock",
  str_detect(laserDirection$remarks, "six o'clock") ~ "6 o'clock",
  str_detect(laserDirection$remarks, "six O'clock") ~ "6 o'clock",
  str_detect(laserDirection$remarks, "6 0'clock") ~ "6 o'clock",
  str_detect(laserDirection$remarks, "6O'Clock") ~ "6 o'clock",
  str_detect(laserDirection$remarks, "7 o'clock") ~ "7 o'clock",  
  str_detect(laserDirection$remarks, "7 O'Clock") ~ "7 o'clock",  
  str_detect(laserDirection$remarks, "7o'clock") ~ "7 o'clock",  
  str_detect(laserDirection$remarks, "7O'Clock") ~ "7 o'clock",  
  str_detect(laserDirection$remarks, "7 O'CLOCK") ~ "7 o'clock",  
  str_detect(laserDirection$remarks, "7 O'clock") ~ "7 o'clock",  
  str_detect(laserDirection$remarks, "seven O'clock") ~ "7 o'clock",  
  str_detect(laserDirection$remarks, "7:30 O'Clock") ~ "7:30 o'clock",  
  str_detect(laserDirection$remarks, "8 o'clock") ~ "8 o'clock",  
  str_detect(laserDirection$remarks, "8 O'Clock") ~ "8 o'clock",
  str_detect(laserDirection$remarks, "8o'clock") ~ "8 o'clock",
  str_detect(laserDirection$remarks, "8 O'clock") ~ "8 o'clock",
  str_detect(laserDirection$remarks, "8O'clock") ~ "8 o'clock",
  str_detect(laserDirection$remarks, "8 oclock") ~ "8 o'clock",
  str_detect(laserDirection$remarks, "8 o 'clock") ~ "8 o'clock",
  str_detect(laserDirection$remarks, "12 O'Clock position and at the 9 O'Clock") ~ "12 and 9 o'clock",
  str_detect(laserDirection$remarks, "9 o'clock") ~ "9 o'clock",  
  str_detect(laserDirection$remarks, "9 O'Clock") ~ "9 o'clock",
  str_detect(laserDirection$remarks, "90'clock") ~ "9 o'clock",
  str_detect(laserDirection$remarks, "9o'clock") ~ "9 o'clock",
  str_detect(laserDirection$remarks, "9 O'clock") ~ "9 o'clock",
  str_detect(laserDirection$remarks, "9 O' Clock") ~ "9 o'clock",
  str_detect(laserDirection$remarks, "9 OClock") ~ "9 o'clock",
  str_detect(laserDirection$remarks, "9O'Clock") ~ "9 o'clock",
  str_detect(laserDirection$remarks, "nine o'clock") ~ "9 o'clock",
  str_detect(laserDirection$remarks, "9O'clock") ~ "9 o'clock",
  str_detect(laserDirection$remarks, "9 O'CLOCK") ~ "9 o'clock",
  str_detect(laserDirection$remarks, "9 0'clock") ~ "9 o'clock",
  str_detect(laserDirection$remarks, "9 oclock") ~ "9 o'clock",
  str_detect(laserDirection$remarks, "9:30") ~ "9:30 o'clock",
  str_detect(laserDirection$remarks, "10 o'clock") ~ "10 o'clock",
  str_detect(laserDirection$remarks, "10 O'Clock") ~ "10 o'clock",
  str_detect(laserDirection$remarks, "10o'clock") ~ "10 o'clock",
  str_detect(laserDirection$remarks, "10O'Clock") ~ "10 o'clock",
  str_detect(laserDirection$remarks, "10 O'clock") ~ "10 o'clock",
  str_detect(laserDirection$remarks, "1O'Clock") ~ "10 o'clock",
  str_detect(laserDirection$remarks, "10O'clock") ~ "10 o'clock",
  str_detect(laserDirection$remarks, "1O'clock") ~ "10 o'clock",
  str_detect(laserDirection$remarks, "10 O'CLOCK") ~ "10 o'clock",
  str_detect(laserDirection$remarks, "ten o'clock") ~ "10 o'clock",
  str_detect(laserDirection$remarks, "10 O' Clock") ~ "10 o'clock",
  str_detect(laserDirection$remarks, "10 o;clock") ~ "10 o'clock",
  str_detect(laserDirection$remarks, "10:30 position") ~ "10:30 clock",
  str_detect(laserDirection$remarks, "from 10:30") ~ "10:30 clock",
  str_detect(laserDirection$remarks, "11:30 position") ~ "11:30 o'clock",
          TRUE ~ as.character(laserDirection$laserClockDir))

#creates a column of directions - right, left, front, etc.

laserDirection$laserDir <- "na"


laserDirection$laserDir <- case_when(
  str_detect(laserDirection$remarks, "right rear") ~  "right back side", 
  str_detect(laserDirection$remarks, "right front") ~ "front right side", 
  str_detect(laserDirection$remarks, "right to left") ~  "right to left side",
  str_detect(laserDirection$remarks, "ahead and to the right") ~ "front right side", 
  str_detect(laserDirection$remarks, "right side") ~ "right side", 
  str_detect(laserDirection$remarks, "Right side") ~ "right side", 
  str_detect(laserDirection$remarks, "from the right") ~  "right side",
  str_detect(laserDirection$remarks, "fromtheright") ~  "right side",
  str_detect(laserDirection$remarks, "RIGHT SIDE") ~  "right side",
  str_detect(laserDirection$remarks, "RIGHT side") ~  "right side",
  str_detect(laserDirection$remarks, "LASER from right") ~  "right side",
  str_detect(laserDirection$remarks, "laser from right") ~  "right side",
  str_detect(laserDirection$remarks, "emanatingfrom right") ~  "right side",
  str_detect(laserDirection$remarks, "laser, from right") ~  "right side",
  str_detect(laserDirection$remarks, "Laser from right") ~  "right side",
  str_detect(laserDirection$remarks, "laser (color unknown) from right") ~  "right side",
  str_detect(laserDirection$remarks, "fromright") ~  "right side",
  str_detect(laserDirection$remarks, "From right") ~  "right side",
  str_detect(laserDirection$remarks, "FROM RIGHT") ~  "right side",
  str_detect(laserDirection$remarks, "off to the right") ~  "right side",
  str_detect(laserDirection$remarks, "from theright") ~  "right side",
  str_detect(laserDirection$remarks, "fromthe right") ~  "right side",
  str_detect(laserDirection$remarks, "form the right") ~  "right side",
  str_detect(laserDirection$remarks, "laser on right") ~  "right side",
  str_detect(laserDirection$remarks, "LASER, from right") ~  "right side",
  str_detect(laserDirection$remarks, "laser originated from right") ~  "right side",
  str_detect(laserDirection$remarks, "laser on the right") ~  "right side",
  str_detect(laserDirection$remarks, "from the R side") ~  "right side",
  str_detect(laserDirection$remarks, "FROM THE RIGHT") ~  "right side",
  str_detect(laserDirection$remarks, "right of the cockpit") ~  "right side",
  str_detect(laserDirection$remarks, "Rightside") ~  "right side",
  str_detect(laserDirection$remarks, "from just right") ~  "right side",
  str_detect(laserDirection$remarks, "illuminated right") ~  "right side",
  str_detect(laserDirection$remarks, "illuminated on the right") ~  "right side",
  str_detect(laserDirection$remarks, "from the R rear") ~  "right back side",
  str_detect(laserDirection$remarks, "from the R") ~  "right side",
  str_detect(laserDirection$remarks, "from theR") ~  "right side",
  str_detect(laserDirection$remarks, "from the rigth") ~  "right side",
  str_detect(laserDirection$remarks, "from the southeast") ~  "southeast side", 
  str_detect(laserDirection$remarks, "LASER fromSE") ~  "southeast side", 
  str_detect(laserDirection$remarks, "from southwest") ~  "southwest side", 
  str_detect(laserDirection$remarks, "LASER from the SW") ~  "southwest side", 
  str_detect(laserDirection$remarks, "Laser from the SW") ~  "southwest side", 
  str_detect(laserDirection$remarks, "from the northeast") ~  "northeast side", 
  str_detect(laserDirection$remarks, "from the NE to SW side") ~  "northeast to southwest side", 
  str_detect(laserDirection$remarks, "from the NE") ~  "northeast side", 
  str_detect(laserDirection$remarks, "from northeast") ~  "northeast side", 
  str_detect(laserDirection$remarks, "from the Northeast") ~  "northeast side", 
  str_detect(laserDirection$remarks, "from the SE") ~  "southeast side", 
  str_detect(laserDirection$remarks, "from the Southeast") ~  "southeast side", 
  str_detect(laserDirection$remarks, "from northwest") ~  "northwest side", 
  str_detect(laserDirection$remarks, "LASER from the NW") ~  "northwest side", 
  str_detect(laserDirection$remarks, "from the Northwest") ~  "northwest side", 
  str_detect(laserDirection$remarks, "from north to south") ~  "north to south side", 
  str_detect(laserDirection$remarks, "fromS toN") ~  "south to north side", 
  str_detect(laserDirection$remarks, "fromsouth to north") ~  "south to north side", 
  str_detect(laserDirection$remarks, "LASER from the ESE") ~  "East SouthEast side", 
  str_detect(laserDirection$remarks, "LASER from the ENE") ~  "East NorthEast side", 
  str_detect(laserDirection$remarks, "LASER from the NNW") ~  "North NorthWest side", 
  str_detect(laserDirection$remarks, "LASER from the S-SW") ~  "South Southwest side", 
  str_detect(laserDirection$remarks, "LASER from theNW") ~  "northwest side", 
  str_detect(laserDirection$remarks, "LASER from theNE") ~  "northeast side", 
  str_detect(laserDirection$remarks, "LASER from theSW") ~  "southwest side", 
  str_detect(laserDirection$remarks, "LASER from theSE") ~  "sourtheast side", 
  str_detect(laserDirection$remarks, "one from behind and one from the front") ~  
    "one behind and one front", 
  str_detect(laserDirection$remarks, "thefront-left") ~  "front left side",  
  str_detect(laserDirection$remarks, "L front side") ~  "front left side",  
  str_detect(laserDirection$remarks, "left front") ~  "front left side",  
  str_detect(laserDirection$remarks, "left side") ~  "left side",
  str_detect(laserDirection$remarks, "from the left") ~  "left side", 
  str_detect(laserDirection$remarks, "Left side") ~  "left side", 
  str_detect(laserDirection$remarks, "leftside") ~  "left side", 
  str_detect(laserDirection$remarks, "left wing") ~  "left side", 
  str_detect(laserDirection$remarks, "left to right") ~  "left to right side", 
  str_detect(laserDirection$remarks, "from left below") ~  "left underside", 
  str_detect(laserDirection$remarks, "below and left") ~  "left underside", 
  str_detect(laserDirection$remarks, "from left") ~  "left side", 
  str_detect(laserDirection$remarks, "to the left") ~  "left side", 
  str_detect(laserDirection$remarks, "LEFT SIDE") ~  "left side", 
  str_detect(laserDirection$remarks, "LEFT side") ~  "left side", 
  str_detect(laserDirection$remarks, "from theleft") ~  "left side", 
  str_detect(laserDirection$remarks, "from the Left") ~  "left side", 
  str_detect(laserDirection$remarks, "form the left") ~  "left side", 
  str_detect(laserDirection$remarks, "from the let side") ~  "left side", 
  str_detect(laserDirection$remarks, "from thelet side") ~  "left side", 
  str_detect(laserDirection$remarks, "FROM LEFT") ~  "left side", 
  str_detect(laserDirection$remarks, "the L side") ~  "left side", 
  str_detect(laserDirection$remarks, "Leftside") ~  "left side", 
  str_detect(laserDirection$remarks, "fromthe left") ~  "left side", 
  str_detect(laserDirection$remarks, "off the left") ~  "left side", 
  str_detect(laserDirection$remarks, "off left") ~  "left side", 
  str_detect(laserDirection$remarks, "of left") ~  "left side", 
  str_detect(laserDirection$remarks, "left down") ~  "left side", 
  str_detect(laserDirection$remarks, "fromleft") ~  "left side", 
  str_detect(laserDirection$remarks, "at the left") ~  "left side", 
  str_detect(laserDirection$remarks, "LEFTside") ~  "left side", 
  str_detect(laserDirection$remarks, "from thel side") ~  "left side", 
  str_detect(laserDirection$remarks, "from theL side") ~  "left side", 
  str_detect(laserDirection$remarks, "from the Lside") ~  "left side", 
  str_detect(laserDirection$remarks, "from thekeft side") ~  "left side", 
  str_detect(laserDirection$remarks, "from thelfet side") ~  "left side", 
  str_detect(laserDirection$remarks, "from straight ahead") ~  "front side", 
  str_detect(laserDirection$remarks, "from the front") ~  "front side", 
  str_detect(laserDirection$remarks, "from ahead") ~  "front side", 
  str_detect(laserDirection$remarks, "from the ahead") ~  "front side", 
  str_detect(laserDirection$remarks, "directly ahead") ~  "front side", 
  str_detect(laserDirection$remarks, "off the nose") ~  "front side", 
  str_detect(laserDirection$remarks, "off nose") ~  "front side", 
  str_detect(laserDirection$remarks, "from the nose") ~  "front side", 
  str_detect(laserDirection$remarks, "of the nose") ~  "front side", 
  str_detect(laserDirection$remarks, "on the nose") ~  "front side", 
  str_detect(laserDirection$remarks, "off its nose") ~  "front side", 
  str_detect(laserDirection$remarks, "off of nose") ~  "front side", 
  str_detect(laserDirection$remarks, "nose of the cockpit") ~  "front side", 
  str_detect(laserDirection$remarks, "nose of ACFT") ~  "front side", 
  str_detect(laserDirection$remarks, "nose of the ACFT") ~  "front side", 
  str_detect(laserDirection$remarks, "laser on nose") ~  "front side", 
  str_detect(laserDirection$remarks, "thenose") ~  "front side", 
  str_detect(laserDirection$remarks, "from thefront") ~  "front side", 
  str_detect(laserDirection$remarks, "from the FRONT") ~  "front side", 
  str_detect(laserDirection$remarks, "fromthefront") ~  "front side", 
  str_detect(laserDirection$remarks, "from in front") ~  "front side", 
  str_detect(laserDirection$remarks, "front of ACFT") ~  "front side", 
  str_detect(laserDirection$remarks, "offits nose") ~  "front side", 
  str_detect(laserDirection$remarks, "from front") ~  "front side", 
  str_detect(laserDirection$remarks, "front of the aircraft") ~  "front side", 
  str_detect(laserDirection$remarks, "front of aircraft") ~  "front side", 
  str_detect(laserDirection$remarks, "front ofaircraft") ~  "front side", 
  str_detect(laserDirection$remarks, "front of cockpit") ~  "front side", 
  str_detect(laserDirection$remarks, "front of the cockpit") ~  "front side", 
  str_detect(laserDirection$remarks, "off the front") ~  "front side", 
  str_detect(laserDirection$remarks, "forn teh front") ~  "front side", 
  str_detect(laserDirection$remarks, "ACFT front") ~  "front side", 
  str_detect(laserDirection$remarks, "frontofaircraft") ~  "front side", 
  str_detect(laserDirection$remarks, "Front side") ~  "front side", 
  str_detect(laserDirection$remarks, "FRONT side") ~  "front side", 
  str_detect(laserDirection$remarks, "fromfront") ~  "front side", 
  str_detect(laserDirection$remarks, "fromthe front") ~  "front side", 
  str_detect(laserDirection$remarks, "front end") ~  "front side", 
  str_detect(laserDirection$remarks, "form the front") ~  "front side", 
  str_detect(laserDirection$remarks, "fromstraight") ~  "front side", 
  str_detect(laserDirection$remarks, "from the forward") ~  "front side", 
  str_detect(laserDirection$remarks, "laser straight on") ~  "front side", 
  str_detect(laserDirection$remarks, "LASER from the straight") ~  "front side", 
  str_detect(laserDirection$remarks, "LASER from straight") ~  "front side", 
  str_detect(laserDirection$remarks, "LASER straight") ~  "front side", 
  str_detect(laserDirection$remarks, "form straight ahead") ~  "front side", 
  str_detect(laserDirection$remarks, "from head-on") ~  "front side", 
  str_detect(laserDirection$remarks, "from the FR side") ~  "front side", 
  str_detect(laserDirection$remarks, "from the rear") ~  "back side", 
  str_detect(laserDirection$remarks, "from behind") ~  "back side", 
  str_detect(laserDirection$remarks, "from the behind") ~  "back side", 
  str_detect(laserDirection$remarks, "from thebehind") ~  "back side", 
  str_detect(laserDirection$remarks, "frombehind") ~  "back side", 
  str_detect(laserDirection$remarks, "boundbehind") ~  "back side", 
  str_detect(laserDirection$remarks, "from the back") ~  "back side", 
  str_detect(laserDirection$remarks, "from therear") ~  "back side", 
  str_detect(laserDirection$remarks, "underside") ~  "underside", 
  str_detect(laserDirection$remarks, "underneath") ~  "underside", 
  str_detect(laserDirection$remarks, "from below") ~  "underside", 
  str_detect(laserDirection$remarks, "frombelow") ~  "underside", 
  str_detect(laserDirection$remarks, "from the below") ~  "underside", 
  str_detect(laserDirection$remarks, "from thebelow") ~  "underside", 
  str_detect(laserDirection$remarks, "directly below") ~  "underside", 
  str_detect(laserDirection$remarks, "directlybelow") ~  "underside", 
  str_detect(laserDirection$remarks, "directly under") ~  "underside", 
  str_detect(laserDirection$remarks, "directly beneath") ~  "underside", 
  str_detect(laserDirection$remarks, "from beneath") ~  "underside", 
  str_detect(laserDirection$remarks, "from the beneath") ~  "underside", 
  str_detect(laserDirection$remarks, "below the aircraft") ~  "underside", 
  str_detect(laserDirection$remarks, "thebelow side") ~  "underside", 
  str_detect(laserDirection$remarks, "LASER fro below") ~  "underside", 
  str_detect(laserDirection$remarks, "directlybelow") ~  "underside", 
  str_detect(laserDirection$remarks, "from BELOW") ~  "underside", 
  str_detect(laserDirection$remarks, "LASERbelow") ~  "underside", 
  str_detect(laserDirection$remarks, "from thebottom") ~  "underside", 
  str_detect(laserDirection$remarks, "from the bottom") ~  "underside", 
  str_detect(laserDirection$remarks, "from theunder side") ~  "underside", 
  str_detect(laserDirection$remarks, "from under aircraft") ~  "underside", 
  str_detect(laserDirection$remarks, "frombeneath") ~  "underside", 
  str_detect(laserDirection$remarks, "rightside") ~  "right side", 
  str_detect(laserDirection$remarks, "from south to north") ~  "south to north side", 
  str_detect(laserDirection$remarks, "from the south") ~  "south side", 
  str_detect(laserDirection$remarks, "from south") ~  "south side", 
  str_detect(laserDirection$remarks, "from South") ~  "south side", 
  str_detect(laserDirection$remarks, "from thesouth") ~  "south side", 
  str_detect(laserDirection$remarks, "from theSouth") ~  "south side", 
  str_detect(laserDirection$remarks, "LASER from the S") ~  "south side", 
  str_detect(laserDirection$remarks, "south side of ACFT") ~  "south side", 
  str_detect(laserDirection$remarks, "from the South") ~  "south side", 
  str_detect(laserDirection$remarks, "from theS position") ~  "south side", 
  str_detect(laserDirection$remarks, "from the north") ~  "north side", 
  str_detect(laserDirection$remarks, "from theNorth") ~  "north side", 
  str_detect(laserDirection$remarks, "from thenorth") ~  "north side", 
  str_detect(laserDirection$remarks, "from the N side") ~  "north side", 
  str_detect(laserDirection$remarks, "thenorth side") ~  "north side", 
  str_detect(laserDirection$remarks, "from north") ~  "north side", 
  str_detect(laserDirection$remarks, "from the North") ~  "north side", 
  str_detect(laserDirection$remarks, "form the north") ~  "north side", 
  str_detect(laserDirection$remarks, "pilot's side") ~  "pilot's side", 
  str_detect(laserDirection$remarks, "LASER from west to east") ~  "west to east side", 
  str_detect(laserDirection$remarks, "from west to east") ~  "west to east side", 
  str_detect(laserDirection$remarks, "from East to West") ~  "west to east side", 
  str_detect(laserDirection$remarks, "LASER came from west to east") ~  "west to east side", 
  str_detect(laserDirection$remarks, "from east to west") ~  "east to west side", 
  str_detect(laserDirection$remarks, "from the East to the West") ~  "east to west side", 
  str_detect(laserDirection$remarks, "from the west") ~  "west side", 
  str_detect(laserDirection$remarks, "from the West") ~  "west side", 
  str_detect(laserDirection$remarks, "from thewest") ~  "west side", 
  str_detect(laserDirection$remarks, "from west") ~  "west side", 
  str_detect(laserDirection$remarks, "from theW side") ~  "west side", 
  str_detect(laserDirection$remarks, "from the W side") ~  "west side", 
  str_detect(laserDirection$remarks, "LASER from the W") ~  "west side", 
  str_detect(laserDirection$remarks, "laser from the W") ~  "west side", 
  str_detect(laserDirection$remarks, "LASER fromwest") ~  "west side", 
  str_detect(laserDirection$remarks, "from the east") ~  "east side", 
  str_detect(laserDirection$remarks, "laser from east") ~  "east side", 
  str_detect(laserDirection$remarks, "east of the ACFT") ~  "east side", 
  str_detect(laserDirection$remarks, "LASER from the E") ~  "east side", 
  str_detect(laserDirection$remarks, "LASER from theE") ~  "east side", 
  str_detect(laserDirection$remarks, "LASER from theeast") ~  "east side", 
  str_detect(laserDirection$remarks, "fromvarious angles") ~  "all sides", 
  str_detect(laserDirection$remarks, "from various sides") ~  "all sides", 
  str_detect(laserDirection$remarks, "both sides") ~  "all sides", 
  str_detect(laserDirection$remarks, "frombothsides") ~  "all sides", 
  str_detect(laserDirection$remarks, "all sides") ~  "all sides", 
  TRUE ~ as.character(laserDirection$laserDir))

laserDirection$laserClockDir <- (case_when(
  str_detect(laserDirection$laserClockDir, "not reported") & str_detect(laserDirection$laserDir, "left to right side") ~ "moving", 
  str_detect(laserDirection$laserClockDir, "not reported") & str_detect(laserDirection$laserDir, "right to left side") ~ "moving",  
  str_detect(laserDirection$laserClockDir, "not reported") & str_detect(laserDirection$laserDir, "front side") ~ "12 o'clock", 
  str_detect(laserDirection$laserClockDir, "not reported") & str_detect(laserDirection$laserDir, "front right side") ~ "1:30 o'clock", 
  str_detect(laserDirection$laserClockDir, "not reported") & str_detect(laserDirection$laserDir, "right side") ~ "3 o'clock",
  str_detect(laserDirection$laserClockDir, "not reported") & str_detect(laserDirection$laserDir, "front left side") ~ "10:30 o'clock",
  str_detect(laserDirection$laserClockDir, "not reported") & str_detect(laserDirection$laserDir, "left side") ~ "9 o'clock",  
  str_detect(laserDirection$laserClockDir, "not reported") & str_detect(laserDirection$laserDir, "pilot side") ~ "9 o'clock",    
  str_detect(laserDirection$laserClockDir, "not reported") & str_detect(laserDirection$laserDir, "right back side") ~ "4:30 o'clock",  
  str_detect(laserDirection$laserClockDir, "not reported") & str_detect(laserDirection$laserDir, "back side") ~ "6 o'clock",
  TRUE ~ as.character(laserDirection$laserClockDir)))

#read in aircraft directions to determine cardinal direction of the laser strike

aircraftDir <- read.csv("C:/laser-acft-dir-extract_20Mar2021.csv", header = TRUE)

fullDirection <- merge(laserDirection, aircraftDir, by = 'ï..X_id')

fullDirection$cardinalLaserDir <- "na"

#12 o'clock
fullDirection$cardinalLaserDir <- (case_when(
  str_detect(fullDirection$laserClockDir, "12 o'clock") & str_detect(fullDirection$Acft_Dir, "ENE") ~ "ENE",
  str_detect(fullDirection$laserClockDir, "12 o'clock") & str_detect(fullDirection$Acft_Dir, "NNE") ~ "NNE",
  str_detect(fullDirection$laserClockDir, "12 o'clock") & str_detect(fullDirection$Acft_Dir, "NE") ~ "NE",
  str_detect(fullDirection$laserClockDir, "12 o'clock") & str_detect(fullDirection$Acft_Dir, "WNW") ~ "WNW",
  str_detect(fullDirection$laserClockDir, "12 o'clock") & str_detect(fullDirection$Acft_Dir, "NNW") ~ "NNW",
  str_detect(fullDirection$laserClockDir, "12 o'clock") & str_detect(fullDirection$Acft_Dir, "NW") ~ "NW",  
  str_detect(fullDirection$laserClockDir, "12 o'clock") & str_detect(fullDirection$Acft_Dir, "N") ~ "N",
  str_detect(fullDirection$laserClockDir, "12 o'clock") & str_detect(fullDirection$Acft_Dir, "SSW") ~ "SSW",  
  str_detect(fullDirection$laserClockDir, "12 o'clock") & str_detect(fullDirection$Acft_Dir, "WSW") ~ "WSW",
  str_detect(fullDirection$laserClockDir, "12 o'clock") & str_detect(fullDirection$Acft_Dir, "SW") ~ "SW",  
  str_detect(fullDirection$laserClockDir, "12 o'clock") & str_detect(fullDirection$Acft_Dir, "W") ~ "W",
  str_detect(fullDirection$laserClockDir, "12 o'clock") & str_detect(fullDirection$Acft_Dir, "ESE") ~ "ESE",
  str_detect(fullDirection$laserClockDir, "12 o'clock") & str_detect(fullDirection$Acft_Dir, "SSE") ~ "SSE",
  str_detect(fullDirection$laserClockDir, "12 o'clock") & str_detect(fullDirection$Acft_Dir, "SE") ~ "SE",
  str_detect(fullDirection$laserClockDir, "12 o'clock") & str_detect(fullDirection$Acft_Dir, "E") ~ "E",
  str_detect(fullDirection$laserClockDir, "12 o'clock") & str_detect(fullDirection$Acft_Dir, "S") ~ "S",
  TRUE ~ as.character(fullDirection$cardinalLaserDir)))

#6 o'clock
fullDirection$cardinalLaserDir <- (case_when(
  str_detect(fullDirection$laserClockDir, "6 o'clock") & str_detect(fullDirection$Acft_Dir, "ENE") ~ "WSW",
  str_detect(fullDirection$laserClockDir, "6 o'clock") & str_detect(fullDirection$Acft_Dir, "NNE") ~ "SSW",
  str_detect(fullDirection$laserClockDir, "6 o'clock") & str_detect(fullDirection$Acft_Dir, "NE") ~ "SW",
  str_detect(fullDirection$laserClockDir, "6 o'clock") & str_detect(fullDirection$Acft_Dir, "NNW") ~ "SSE",
  str_detect(fullDirection$laserClockDir, "6 o'clock") & str_detect(fullDirection$Acft_Dir, "NW") ~ "SE",  
  str_detect(fullDirection$laserClockDir, "6 o'clock") & str_detect(fullDirection$Acft_Dir, "N") ~ "S",
  str_detect(fullDirection$laserClockDir, "6 o'clock") & str_detect(fullDirection$Acft_Dir, "SSW") ~ "NNE",  
  str_detect(fullDirection$laserClockDir, "6 o'clock") & str_detect(fullDirection$Acft_Dir, "WSW") ~ "ENE",
  str_detect(fullDirection$laserClockDir, "6 o'clock") & str_detect(fullDirection$Acft_Dir, "SW") ~ "NE",  
  str_detect(fullDirection$laserClockDir, "6 o'clock") & str_detect(fullDirection$Acft_Dir, "W") ~ "E",
  str_detect(fullDirection$laserClockDir, "6 o'clock") & str_detect(fullDirection$Acft_Dir, "ESE") ~ "WNW",
  str_detect(fullDirection$laserClockDir, "6 o'clock") & str_detect(fullDirection$Acft_Dir, "SSE") ~ "NNW",
  str_detect(fullDirection$laserClockDir, "6 o'clock") & str_detect(fullDirection$Acft_Dir, "SE") ~ "NW",
  str_detect(fullDirection$laserClockDir, "6 o'clock") & str_detect(fullDirection$Acft_Dir, "E") ~ "W",
  str_detect(fullDirection$laserClockDir, "6 o'clock") & str_detect(fullDirection$Acft_Dir, "S") ~ "N",
  TRUE ~ as.character(fullDirection$cardinalLaserDir)))

#3 o'clock
fullDirection$cardinalLaserDir <- (case_when(
  str_detect(fullDirection$laserClockDir, "3 o'clock") & str_detect(fullDirection$Acft_Dir, "ENE") ~ "SSE",
  str_detect(fullDirection$laserClockDir, "3 o'clock") & str_detect(fullDirection$Acft_Dir, "NNE") ~ "ESE",
  str_detect(fullDirection$laserClockDir, "3 o'clock") & str_detect(fullDirection$Acft_Dir, "NE") ~ "SE",
  str_detect(fullDirection$laserClockDir, "3 o'clock") & str_detect(fullDirection$Acft_Dir, "WNW") ~ "NNE",  
  str_detect(fullDirection$laserClockDir, "3 o'clock") & str_detect(fullDirection$Acft_Dir, "NNW") ~ "ENE",
  str_detect(fullDirection$laserClockDir, "3 o'clock") & str_detect(fullDirection$Acft_Dir, "NW") ~ "NE",  
  str_detect(fullDirection$laserClockDir, "3 o'clock") & str_detect(fullDirection$Acft_Dir, "N") ~ "E",
  str_detect(fullDirection$laserClockDir, "3 o'clock") & str_detect(fullDirection$Acft_Dir, "SSW") ~ "WNW",  
  str_detect(fullDirection$laserClockDir, "3 o'clock") & str_detect(fullDirection$Acft_Dir, "WSW") ~ "NNW",
  str_detect(fullDirection$laserClockDir, "3 o'clock") & str_detect(fullDirection$Acft_Dir, "SW") ~ "NW",  
  str_detect(fullDirection$laserClockDir, "3 o'clock") & str_detect(fullDirection$Acft_Dir, "W") ~ "N",
  str_detect(fullDirection$laserClockDir, "3 o'clock") & str_detect(fullDirection$Acft_Dir, "ESE") ~ "SSW",
  str_detect(fullDirection$laserClockDir, "3 o'clock") & str_detect(fullDirection$Acft_Dir, "SSE") ~ "WSW",
  str_detect(fullDirection$laserClockDir, "3 o'clock") & str_detect(fullDirection$Acft_Dir, "SE") ~ "SW",
  str_detect(fullDirection$laserClockDir, "3 o'clock") & str_detect(fullDirection$Acft_Dir, "E") ~ "S",
  str_detect(fullDirection$laserClockDir, "3 o'clock") & str_detect(fullDirection$Acft_Dir, "S") ~ "W",
  TRUE ~ as.character(fullDirection$cardinalLaserDir)))

#9 o'clock
fullDirection$cardinalLaserDir <- (case_when(
  str_detect(fullDirection$laserClockDir, "9 o'clock") & str_detect(fullDirection$Acft_Dir, "ENE") ~ "NNW",
  str_detect(fullDirection$laserClockDir, "9 o'clock") & str_detect(fullDirection$Acft_Dir, "NNE") ~ "WNW",
  str_detect(fullDirection$laserClockDir, "9 o'clock") & str_detect(fullDirection$Acft_Dir, "NE") ~ "NW",
  str_detect(fullDirection$laserClockDir, "9 o'clock") & str_detect(fullDirection$Acft_Dir, "WNW") ~ "SSW",  
  str_detect(fullDirection$laserClockDir, "9 o'clock") & str_detect(fullDirection$Acft_Dir, "NNW") ~ "WSW",
  str_detect(fullDirection$laserClockDir, "9 o'clock") & str_detect(fullDirection$Acft_Dir, "NW") ~ "SW",  
  str_detect(fullDirection$laserClockDir, "9 o'clock") & str_detect(fullDirection$Acft_Dir, "N") ~ "W",
  str_detect(fullDirection$laserClockDir, "9 o'clock") & str_detect(fullDirection$Acft_Dir, "SSW") ~ "ESE",  
  str_detect(fullDirection$laserClockDir, "9 o'clock") & str_detect(fullDirection$Acft_Dir, "WSW") ~ "SSE",
  str_detect(fullDirection$laserClockDir, "9 o'clock") & str_detect(fullDirection$Acft_Dir, "SW") ~ "SE",  
  str_detect(fullDirection$laserClockDir, "9 o'clock") & str_detect(fullDirection$Acft_Dir, "W") ~ "S",
  str_detect(fullDirection$laserClockDir, "9 o'clock") & str_detect(fullDirection$Acft_Dir, "NNE") ~ "SSW",
  str_detect(fullDirection$laserClockDir, "9 o'clock") & str_detect(fullDirection$Acft_Dir, "ENE") ~ "WSW",
  str_detect(fullDirection$laserClockDir, "9 o'clock") & str_detect(fullDirection$Acft_Dir, "SE") ~ "NE",
  str_detect(fullDirection$laserClockDir, "9 o'clock") & str_detect(fullDirection$Acft_Dir, "E") ~ "N",
  str_detect(fullDirection$laserClockDir, "9 o'clock") & str_detect(fullDirection$Acft_Dir, "S") ~ "E",
  TRUE ~ as.character(fullDirection$cardinalLaserDir)))

fullDirection$cardinalLaserDir <- (case_when(
  str_detect(fullDirection$laserDir, "East NorthEast side") ~ "ENE", 
  str_detect(fullDirection$laserDir, "East SouthEast side") ~ "ESE", 
  str_detect(fullDirection$laserDir, "North NorthWest side") ~ "NNW", 
  str_detect(fullDirection$laserDir, "South Southwest side") ~ "SSW", 
  str_detect(fullDirection$laserDir, "east to west side") ~ "moving E to W", 
  str_detect(fullDirection$laserDir, "north to south side") ~ "moving N to S", 
  str_detect(fullDirection$laserDir, "northeast to southwest side") ~ "moving NE to SW", 
  str_detect(fullDirection$laserDir, "south to north side") ~ "moving S to N", 
  str_detect(fullDirection$laserDir, "west to east side") ~ "moving W to E", 
  str_detect(fullDirection$laserDir, "northeast side") ~ "NE", 
  str_detect(fullDirection$laserDir, "northwest side") ~ "NW", 
  str_detect(fullDirection$laserDir, "southeast side") ~ "SE", 
  str_detect(fullDirection$laserDir, "southwest side") ~ "SW", 
  str_detect(fullDirection$laserDir, "east side") ~ "E", 
  str_detect(fullDirection$laserDir, "west side") ~ "W", 
  str_detect(fullDirection$laserDir, "south side") ~ "S", 
  str_detect(fullDirection$laserDir, "north side") ~ "N", 
  TRUE ~ as.character(fullDirection$cardinalLaserDir)))

fullDirection$degreeLaserDir <- "na"

#add degree information to lasers cardinal direction

fullDirection$degreeLaserDir <- (case_when(
  str_detect(fullDirection$cardinalLaserDir, "ENE") ~ "67.5", 
  str_detect(fullDirection$cardinalLaserDir, "ESE") ~ "112.5", 
  str_detect(fullDirection$cardinalLaserDir, "NNW") ~ "337.5", 
  str_detect(fullDirection$cardinalLaserDir, "SSW") ~ "202.5", 
  str_detect(fullDirection$cardinalLaserDir, "moving E to W") ~ "90 to 270", 
  str_detect(fullDirection$cardinalLaserDir, "moving N to S") ~ "0 to 180", 
  str_detect(fullDirection$cardinalLaserDir, "moving NE to SW") ~ "45 to 225", 
  str_detect(fullDirection$cardinalLaserDir, "moving S to N") ~ "180 to 0", 
  str_detect(fullDirection$cardinalLaserDir, "moving W to E") ~ "270 to 90", 
  str_detect(fullDirection$cardinalLaserDir, "NE") ~ "45", 
  str_detect(fullDirection$cardinalLaserDir, "NW") ~ "315", 
  str_detect(fullDirection$cardinalLaserDir, "SE") ~ "135", 
  str_detect(fullDirection$cardinalLaserDir, "SW") ~ "225", 
  str_detect(fullDirection$cardinalLaserDir, "E") ~ "90", 
  str_detect(fullDirection$cardinalLaserDir, "W") ~ "270", 
  str_detect(fullDirection$cardinalLaserDir, "S") ~ "180", 
  str_detect(fullDirection$cardinalLaserDir, "N") ~ "0", 
  TRUE ~ as.character(fullDirection$degreeLaserDir)))


#adding in degrees for laser in relationship to the aircraft 
fullDirection$degreeLaserDir <- (case_when(
  str_detect(fullDirection$laserClockDir, "12 o'clock")  ~ as.character(fullDirection$degreeLaserDir),
  str_detect(fullDirection$laserClockDir, "11 o'clock") & str_detect(fullDirection$Acft_Dir, "ENE") ~ "37.5",
  str_detect(fullDirection$laserClockDir, "11 o'clock") & str_detect(fullDirection$Acft_Dir, "NNE") ~ "352.5",
  str_detect(fullDirection$laserClockDir, "11 o'clock") & str_detect(fullDirection$Acft_Dir, "NE") ~ "15",
  str_detect(fullDirection$laserClockDir, "11 o'clock") & str_detect(fullDirection$Acft_Dir, "WNW") ~ "262.5",
  str_detect(fullDirection$laserClockDir, "11 o'clock") & str_detect(fullDirection$Acft_Dir, "NNW") ~ "307.5",
  str_detect(fullDirection$laserClockDir, "11 o'clock") & str_detect(fullDirection$Acft_Dir, "NW") ~ "285",  
  str_detect(fullDirection$laserClockDir, "11 o'clock") & str_detect(fullDirection$Acft_Dir, "N") ~ "330",
  str_detect(fullDirection$laserClockDir, "11 o'clock") & str_detect(fullDirection$Acft_Dir, "SSW") ~ "172.5",
  str_detect(fullDirection$laserClockDir, "11 o'clock") & str_detect(fullDirection$Acft_Dir, "WSW") ~ "217.5",
  str_detect(fullDirection$laserClockDir, "11 o'clock") & str_detect(fullDirection$Acft_Dir, "SW") ~ "195",  
  str_detect(fullDirection$laserClockDir, "11 o'clock") & str_detect(fullDirection$Acft_Dir, "W") ~ "240",
  str_detect(fullDirection$laserClockDir, "11 o'clock") & str_detect(fullDirection$Acft_Dir, "ESE") ~ "82.5",
  str_detect(fullDirection$laserClockDir, "11 o'clock") & str_detect(fullDirection$Acft_Dir, "SSE") ~ "127.5",
  str_detect(fullDirection$laserClockDir, "11 o'clock") & str_detect(fullDirection$Acft_Dir, "SE") ~ "105",
  str_detect(fullDirection$laserClockDir, "11 o'clock") & str_detect(fullDirection$Acft_Dir, "E") ~ "60",
  str_detect(fullDirection$laserClockDir, "11 o'clock") & str_detect(fullDirection$Acft_Dir, "S") ~ "150",
  str_detect(fullDirection$laserClockDir, "10 o'clock") & str_detect(fullDirection$Acft_Dir, "ENE") ~ "7.5",
  str_detect(fullDirection$laserClockDir, "10 o'clock") & str_detect(fullDirection$Acft_Dir, "NNE") ~ "322.5",
  str_detect(fullDirection$laserClockDir, "10 o'clock") & str_detect(fullDirection$Acft_Dir, "NE") ~ "345",
  str_detect(fullDirection$laserClockDir, "10 o'clock") & str_detect(fullDirection$Acft_Dir, "WNW") ~ "232.5",
  str_detect(fullDirection$laserClockDir, "10 o'clock") & str_detect(fullDirection$Acft_Dir, "NNW") ~ "307.5",
  str_detect(fullDirection$laserClockDir, "10 o'clock") & str_detect(fullDirection$Acft_Dir, "NW") ~ "285",  
  str_detect(fullDirection$laserClockDir, "10 o'clock") & str_detect(fullDirection$Acft_Dir, "N") ~ "300",
  str_detect(fullDirection$laserClockDir, "10 o'clock") & str_detect(fullDirection$Acft_Dir, "SSW") ~ "142.5",
  str_detect(fullDirection$laserClockDir, "10 o'clock") & str_detect(fullDirection$Acft_Dir, "WSW") ~ "187.5",
  str_detect(fullDirection$laserClockDir, "10 o'clock") & str_detect(fullDirection$Acft_Dir, "SW") ~ "165",  
  str_detect(fullDirection$laserClockDir, "10 o'clock") & str_detect(fullDirection$Acft_Dir, "W") ~ "210",
  str_detect(fullDirection$laserClockDir, "10 o'clock") & str_detect(fullDirection$Acft_Dir, "ESE") ~ "52.5",
  str_detect(fullDirection$laserClockDir, "10 o'clock") & str_detect(fullDirection$Acft_Dir, "SSE") ~ "97.5",
  str_detect(fullDirection$laserClockDir, "10 o'clock") & str_detect(fullDirection$Acft_Dir, "SE") ~ "75",
  str_detect(fullDirection$laserClockDir, "10 o'clock") & str_detect(fullDirection$Acft_Dir, "E") ~ "30",
  str_detect(fullDirection$laserClockDir, "10 o'clock") & str_detect(fullDirection$Acft_Dir, "S") ~ "120",  
  str_detect(fullDirection$laserClockDir, "3 to 9 o'clock") & str_detect(fullDirection$Acft_Dir, "E") ~ "180 to 0",
  str_detect(fullDirection$laserClockDir, "9 o'clock")  ~ as.character(fullDirection$degreeLaserDir),
  str_detect(fullDirection$laserClockDir, "8 o'clock") & str_detect(fullDirection$Acft_Dir, "ENE") ~ "307.5",
  str_detect(fullDirection$laserClockDir, "8 o'clock") & str_detect(fullDirection$Acft_Dir, "NNE") ~ "262.5",
  str_detect(fullDirection$laserClockDir, "8 o'clock") & str_detect(fullDirection$Acft_Dir, "NE") ~ "285",
  str_detect(fullDirection$laserClockDir, "8 o'clock") & str_detect(fullDirection$Acft_Dir, "WNW") ~ "172.5",
  str_detect(fullDirection$laserClockDir, "8 o'clock") & str_detect(fullDirection$Acft_Dir, "NNW") ~ "217.5",
  str_detect(fullDirection$laserClockDir, "8 o'clock") & str_detect(fullDirection$Acft_Dir, "NW") ~ "195",  
  str_detect(fullDirection$laserClockDir, "8 o'clock") & str_detect(fullDirection$Acft_Dir, "N") ~ "330",
  str_detect(fullDirection$laserClockDir, "8 o'clock") & str_detect(fullDirection$Acft_Dir, "SSW") ~ "82.5",
  str_detect(fullDirection$laserClockDir, "8 o'clock") & str_detect(fullDirection$Acft_Dir, "WSW") ~ "127.5",
  str_detect(fullDirection$laserClockDir, "8 o'clock") & str_detect(fullDirection$Acft_Dir, "SW") ~ "105",  
  str_detect(fullDirection$laserClockDir, "8 o'clock") & str_detect(fullDirection$Acft_Dir, "W") ~ "150",
  str_detect(fullDirection$laserClockDir, "8 o'clock") & str_detect(fullDirection$Acft_Dir, "ESE") ~ "352.5",
  str_detect(fullDirection$laserClockDir, "8 o'clock") & str_detect(fullDirection$Acft_Dir, "SSE") ~ "37.5",
  str_detect(fullDirection$laserClockDir, "8 o'clock") & str_detect(fullDirection$Acft_Dir, "SE") ~ "15",
  str_detect(fullDirection$laserClockDir, "8 o'clock") & str_detect(fullDirection$Acft_Dir, "E") ~ "330",
  str_detect(fullDirection$laserClockDir, "8 o'clock") & str_detect(fullDirection$Acft_Dir, "S") ~ "60",
  str_detect(fullDirection$laserClockDir, "7 o'clock") & str_detect(fullDirection$Acft_Dir, "ENE") ~ "277.5",
  str_detect(fullDirection$laserClockDir, "7 o'clock") & str_detect(fullDirection$Acft_Dir, "NNE") ~ "232.5",
  str_detect(fullDirection$laserClockDir, "7 o'clock") & str_detect(fullDirection$Acft_Dir, "NE") ~ "255",
  str_detect(fullDirection$laserClockDir, "7 o'clock") & str_detect(fullDirection$Acft_Dir, "WNW") ~ "142.5",
  str_detect(fullDirection$laserClockDir, "7 o'clock") & str_detect(fullDirection$Acft_Dir, "NNW") ~ "187.5",
  str_detect(fullDirection$laserClockDir, "7 o'clock") & str_detect(fullDirection$Acft_Dir, "NW") ~ "165",  
  str_detect(fullDirection$laserClockDir, "7 o'clock") & str_detect(fullDirection$Acft_Dir, "N") ~ "210",
  str_detect(fullDirection$laserClockDir, "7 o'clock") & str_detect(fullDirection$Acft_Dir, "SSW") ~ "52.5",
  str_detect(fullDirection$laserClockDir, "7 o'clock") & str_detect(fullDirection$Acft_Dir, "WSW") ~ "97.5",
  str_detect(fullDirection$laserClockDir, "7 o'clock") & str_detect(fullDirection$Acft_Dir, "SW") ~ "75",  
  str_detect(fullDirection$laserClockDir, "7 o'clock") & str_detect(fullDirection$Acft_Dir, "W") ~ "120",
  str_detect(fullDirection$laserClockDir, "7 o'clock") & str_detect(fullDirection$Acft_Dir, "ESE") ~ "322.5",
  str_detect(fullDirection$laserClockDir, "7 o'clock") & str_detect(fullDirection$Acft_Dir, "SSE") ~ "7.5",
  str_detect(fullDirection$laserClockDir, "7 o'clock") & str_detect(fullDirection$Acft_Dir, "SE") ~ "345",
  str_detect(fullDirection$laserClockDir, "7 o'clock") & str_detect(fullDirection$Acft_Dir, "E") ~ "300",
  str_detect(fullDirection$laserClockDir, "7 o'clock") & str_detect(fullDirection$Acft_Dir, "S") ~ "30",  
  str_detect(fullDirection$laserClockDir, "2 to 6 o'clock") & str_detect(fullDirection$Acft_Dir, "S") ~ "240 to 0",
  str_detect(fullDirection$laserClockDir, "2 to 6 o'clock") & str_detect(fullDirection$Acft_Dir, "NW") ~ "15 to 135",
  str_detect(fullDirection$laserClockDir, "6 o'clock")  ~ as.character(fullDirection$degreeLaserDir),
  str_detect(fullDirection$laserClockDir, "5 o'clock") & str_detect(fullDirection$Acft_Dir, "ENE") ~ "217.5",
  str_detect(fullDirection$laserClockDir, "5 o'clock") & str_detect(fullDirection$Acft_Dir, "NNE") ~ "172.5",
  str_detect(fullDirection$laserClockDir, "5 o'clock") & str_detect(fullDirection$Acft_Dir, "NE") ~ "195",
  str_detect(fullDirection$laserClockDir, "5 o'clock") & str_detect(fullDirection$Acft_Dir, "WNW") ~ "82.5",
  str_detect(fullDirection$laserClockDir, "5 o'clock") & str_detect(fullDirection$Acft_Dir, "NNW") ~ "127.5",
  str_detect(fullDirection$laserClockDir, "5 o'clock") & str_detect(fullDirection$Acft_Dir, "NW") ~ "105",  
  str_detect(fullDirection$laserClockDir, "5 o'clock") & str_detect(fullDirection$Acft_Dir, "N") ~ "150",
  str_detect(fullDirection$laserClockDir, "5 o'clock") & str_detect(fullDirection$Acft_Dir, "SSW") ~ "352.5",
  str_detect(fullDirection$laserClockDir, "5 o'clock") & str_detect(fullDirection$Acft_Dir, "WSW") ~ "37.5",
  str_detect(fullDirection$laserClockDir, "5 o'clock") & str_detect(fullDirection$Acft_Dir, "SW") ~ "15",  
  str_detect(fullDirection$laserClockDir, "5 o'clock") & str_detect(fullDirection$Acft_Dir, "W") ~ "60",
  str_detect(fullDirection$laserClockDir, "5 o'clock") & str_detect(fullDirection$Acft_Dir, "ESE") ~ "262.5",
  str_detect(fullDirection$laserClockDir, "5 o'clock") & str_detect(fullDirection$Acft_Dir, "SSE") ~ "307.5",
  str_detect(fullDirection$laserClockDir, "5 o'clock") & str_detect(fullDirection$Acft_Dir, "SE") ~ "285",
  str_detect(fullDirection$laserClockDir, "5 o'clock") & str_detect(fullDirection$Acft_Dir, "E") ~ "240",
  str_detect(fullDirection$laserClockDir, "5 o'clock") & str_detect(fullDirection$Acft_Dir, "S") ~ "330",
  str_detect(fullDirection$laserClockDir, "4 o'clock") & str_detect(fullDirection$Acft_Dir, "ENE") ~ "187.5",
  str_detect(fullDirection$laserClockDir, "4 o'clock") & str_detect(fullDirection$Acft_Dir, "NNE") ~ "142.5",
  str_detect(fullDirection$laserClockDir, "4 o'clock") & str_detect(fullDirection$Acft_Dir, "NE") ~ "165",
  str_detect(fullDirection$laserClockDir, "4 o'clock") & str_detect(fullDirection$Acft_Dir, "WNW") ~ "52.5",
  str_detect(fullDirection$laserClockDir, "4 o'clock") & str_detect(fullDirection$Acft_Dir, "NNW") ~ "97.5",
  str_detect(fullDirection$laserClockDir, "4 o'clock") & str_detect(fullDirection$Acft_Dir, "NW") ~ "75",  
  str_detect(fullDirection$laserClockDir, "4 o'clock") & str_detect(fullDirection$Acft_Dir, "N") ~ "120",
  str_detect(fullDirection$laserClockDir, "4 o'clock") & str_detect(fullDirection$Acft_Dir, "SSW") ~ "322.5",
  str_detect(fullDirection$laserClockDir, "4 o'clock") & str_detect(fullDirection$Acft_Dir, "WSW") ~ "7.5",
  str_detect(fullDirection$laserClockDir, "4 o'clock") & str_detect(fullDirection$Acft_Dir, "SW") ~ "345",  
  str_detect(fullDirection$laserClockDir, "4 o'clock") & str_detect(fullDirection$Acft_Dir, "W") ~ "30",
  str_detect(fullDirection$laserClockDir, "4 o'clock") & str_detect(fullDirection$Acft_Dir, "ESE") ~ "232.5",
  str_detect(fullDirection$laserClockDir, "4 o'clock") & str_detect(fullDirection$Acft_Dir, "SSE") ~ "277.5",
  str_detect(fullDirection$laserClockDir, "4 o'clock") & str_detect(fullDirection$Acft_Dir, "SE") ~ "255",
  str_detect(fullDirection$laserClockDir, "4 o'clock") & str_detect(fullDirection$Acft_Dir, "E") ~ "210",
  str_detect(fullDirection$laserClockDir, "4 o'clock") & str_detect(fullDirection$Acft_Dir, "S") ~ "300",  
  str_detect(fullDirection$laserClockDir, "9 to 3 o'clock") & str_detect(fullDirection$Acft_Dir, "WNW") ~ "202.5 to 22.5",
  str_detect(fullDirection$laserClockDir, "9 to 3 o'clock") & str_detect(fullDirection$Acft_Dir, "SW") ~ "135 to 315",
  str_detect(fullDirection$laserClockDir, "9 to 3 o'clock") & str_detect(fullDirection$Acft_Dir, "W") ~ "180 to 0",
  str_detect(fullDirection$laserClockDir, "9 to 3 o'clock") & str_detect(fullDirection$Acft_Dir, "N") ~ "270 to 90",
  str_detect(fullDirection$laserClockDir, "9 to 3 o'clock") & str_detect(fullDirection$Acft_Dir, "E") ~ "0 to 180",
  str_detect(fullDirection$laserClockDir, "1 to 3 o'clock") & str_detect(fullDirection$Acft_Dir, "W") ~ "300 to 0",
  str_detect(fullDirection$laserClockDir, "2 to 3 o'clock") & str_detect(fullDirection$Acft_Dir, "NE") ~ "105 to 135",
  str_detect(fullDirection$laserClockDir, "3 o'clock")  ~ as.character(fullDirection$degreeLaserDir),
  str_detect(fullDirection$laserClockDir, "2 o'clock") & str_detect(fullDirection$Acft_Dir, "ENE") ~ "127.5",
  str_detect(fullDirection$laserClockDir, "2 o'clock") & str_detect(fullDirection$Acft_Dir, "NNE") ~ "82.5",
  str_detect(fullDirection$laserClockDir, "2 o'clock") & str_detect(fullDirection$Acft_Dir, "NE") ~ "105",
  str_detect(fullDirection$laserClockDir, "2 o'clock") & str_detect(fullDirection$Acft_Dir, "WNW") ~ "352.5",
  str_detect(fullDirection$laserClockDir, "2 o'clock") & str_detect(fullDirection$Acft_Dir, "NNW") ~ "37.5",
  str_detect(fullDirection$laserClockDir, "2 o'clock") & str_detect(fullDirection$Acft_Dir, "NW") ~ "15",  
  str_detect(fullDirection$laserClockDir, "2 o'clock") & str_detect(fullDirection$Acft_Dir, "N") ~ "60",
  str_detect(fullDirection$laserClockDir, "2 o'clock") & str_detect(fullDirection$Acft_Dir, "SSW") ~ "262.5",
  str_detect(fullDirection$laserClockDir, "2 o'clock") & str_detect(fullDirection$Acft_Dir, "WSW") ~ "307.5",
  str_detect(fullDirection$laserClockDir, "2 o'clock") & str_detect(fullDirection$Acft_Dir, "SW") ~ "285",  
  str_detect(fullDirection$laserClockDir, "2 o'clock") & str_detect(fullDirection$Acft_Dir, "W") ~ "330",
  str_detect(fullDirection$laserClockDir, "2 o'clock") & str_detect(fullDirection$Acft_Dir, "ESE") ~ "172.5",
  str_detect(fullDirection$laserClockDir, "2 o'clock") & str_detect(fullDirection$Acft_Dir, "SSE") ~ "217.5",
  str_detect(fullDirection$laserClockDir, "2 o'clock") & str_detect(fullDirection$Acft_Dir, "SE") ~ "195",
  str_detect(fullDirection$laserClockDir, "2 o'clock") & str_detect(fullDirection$Acft_Dir, "E") ~ "150",
  str_detect(fullDirection$laserClockDir, "2 o'clock") & str_detect(fullDirection$Acft_Dir, "S") ~ "240",
  str_detect(fullDirection$laserClockDir, "1 o'clock") & str_detect(fullDirection$Acft_Dir, "ENE") ~ "97.5",
  str_detect(fullDirection$laserClockDir, "1 o'clock") & str_detect(fullDirection$Acft_Dir, "NNE") ~ "52.5",
  str_detect(fullDirection$laserClockDir, "1 o'clock") & str_detect(fullDirection$Acft_Dir, "NE") ~ "75",
  str_detect(fullDirection$laserClockDir, "1 o'clock") & str_detect(fullDirection$Acft_Dir, "WNW") ~ "322.5",
  str_detect(fullDirection$laserClockDir, "1 o'clock") & str_detect(fullDirection$Acft_Dir, "NNW") ~ "7.5",
  str_detect(fullDirection$laserClockDir, "1 o'clock") & str_detect(fullDirection$Acft_Dir, "NW") ~ "345",  
  str_detect(fullDirection$laserClockDir, "1 o'clock") & str_detect(fullDirection$Acft_Dir, "N") ~ "30",
  str_detect(fullDirection$laserClockDir, "1 o'clock") & str_detect(fullDirection$Acft_Dir, "SSW") ~ "232.5",
  str_detect(fullDirection$laserClockDir, "1 o'clock") & str_detect(fullDirection$Acft_Dir, "WSW") ~ "277.5",
  str_detect(fullDirection$laserClockDir, "1 o'clock") & str_detect(fullDirection$Acft_Dir, "SW") ~ "255",  
  str_detect(fullDirection$laserClockDir, "1 o'clock") & str_detect(fullDirection$Acft_Dir, "W") ~ "300",
  str_detect(fullDirection$laserClockDir, "1 o'clock") & str_detect(fullDirection$Acft_Dir, "ESE") ~ "142.5",
  str_detect(fullDirection$laserClockDir, "1 o'clock") & str_detect(fullDirection$Acft_Dir, "SSE") ~ "187.5",
  str_detect(fullDirection$laserClockDir, "1 o'clock") & str_detect(fullDirection$Acft_Dir, "SE") ~ "165",
  str_detect(fullDirection$laserClockDir, "1 o'clock") & str_detect(fullDirection$Acft_Dir, "E") ~ "120",
  str_detect(fullDirection$laserClockDir, "1 o'clock") & str_detect(fullDirection$Acft_Dir, "S") ~ "210",
  str_detect(fullDirection$laserClockDir, "1:30 o'clock") & str_detect(fullDirection$Acft_Dir, "ENE") ~ "112.5",
  str_detect(fullDirection$laserClockDir, "1:30 o'clock") & str_detect(fullDirection$Acft_Dir, "NNE") ~ "67.5",
  str_detect(fullDirection$laserClockDir, "1:30 o'clock") & str_detect(fullDirection$Acft_Dir, "NE") ~ "90",
  str_detect(fullDirection$laserClockDir, "1:30 o'clock") & str_detect(fullDirection$Acft_Dir, "WNW") ~ "337.5",
  str_detect(fullDirection$laserClockDir, "1:30 o'clock") & str_detect(fullDirection$Acft_Dir, "NNW") ~ "22.5",
  str_detect(fullDirection$laserClockDir, "1:30 o'clock") & str_detect(fullDirection$Acft_Dir, "NW") ~ "0",  
  str_detect(fullDirection$laserClockDir, "1:30 o'clock") & str_detect(fullDirection$Acft_Dir, "N") ~ "45",
  str_detect(fullDirection$laserClockDir, "1:30 o'clock") & str_detect(fullDirection$Acft_Dir, "SSW") ~ "247.5",
  str_detect(fullDirection$laserClockDir, "1:30 o'clock") & str_detect(fullDirection$Acft_Dir, "WSW") ~ "292.5",
  str_detect(fullDirection$laserClockDir, "1:30 o'clock") & str_detect(fullDirection$Acft_Dir, "SW") ~ "270",  
  str_detect(fullDirection$laserClockDir, "1:30 o'clock") & str_detect(fullDirection$Acft_Dir, "W") ~ "315",
  str_detect(fullDirection$laserClockDir, "1:30 o'clock") & str_detect(fullDirection$Acft_Dir, "ESE") ~ "157.5",
  str_detect(fullDirection$laserClockDir, "1:30 o'clock") & str_detect(fullDirection$Acft_Dir, "SSE") ~ "202.5",
  str_detect(fullDirection$laserClockDir, "1:30 o'clock") & str_detect(fullDirection$Acft_Dir, "SE") ~ "180",
  str_detect(fullDirection$laserClockDir, "1:30 o'clock") & str_detect(fullDirection$Acft_Dir, "E") ~ "135",
  str_detect(fullDirection$laserClockDir, "1:30 o'clock") & str_detect(fullDirection$Acft_Dir, "S") ~ "225",    str_detect(fullDirection$laserClockDir, "10:30 o'clock") & str_detect(fullDirection$Acft_Dir, "ENE") ~ "22.5",
  str_detect(fullDirection$laserClockDir, "10:30 o'clock") & str_detect(fullDirection$Acft_Dir, "NNE") ~ "337.5",
  str_detect(fullDirection$laserClockDir, "10:30 o'clock") & str_detect(fullDirection$Acft_Dir, "NE") ~ "0",
  str_detect(fullDirection$laserClockDir, "10:30 o'clock") & str_detect(fullDirection$Acft_Dir, "WNW") ~ "247.5",
  str_detect(fullDirection$laserClockDir, "10:30 o'clock") & str_detect(fullDirection$Acft_Dir, "NNW") ~ "292.5",
  str_detect(fullDirection$laserClockDir, "10:30 o'clock") & str_detect(fullDirection$Acft_Dir, "NW") ~ "270",  
  str_detect(fullDirection$laserClockDir, "10:30 o'clock") & str_detect(fullDirection$Acft_Dir, "N") ~ "315",
  str_detect(fullDirection$laserClockDir, "10:30 o'clock") & str_detect(fullDirection$Acft_Dir, "SSW") ~ "157.5",
  str_detect(fullDirection$laserClockDir, "10:30 o'clock") & str_detect(fullDirection$Acft_Dir, "WSW") ~ "202.5",
  str_detect(fullDirection$laserClockDir, "10:30 o'clock") & str_detect(fullDirection$Acft_Dir, "SW") ~ "180",  
  str_detect(fullDirection$laserClockDir, "10:30 o'clock") & str_detect(fullDirection$Acft_Dir, "W") ~ "225",
  str_detect(fullDirection$laserClockDir, "10:30 o'clock") & str_detect(fullDirection$Acft_Dir, "ESE") ~ "67.5",
  str_detect(fullDirection$laserClockDir, "10:30 o'clock") & str_detect(fullDirection$Acft_Dir, "SSE") ~ "112.5",
  str_detect(fullDirection$laserClockDir, "10:30 o'clock") & str_detect(fullDirection$Acft_Dir, "SE") ~ "90",
  str_detect(fullDirection$laserClockDir, "10:30 o'clock") & str_detect(fullDirection$Acft_Dir, "E") ~ "45",
  str_detect(fullDirection$laserClockDir, "10:30 o'clock") & str_detect(fullDirection$Acft_Dir, "S") ~ "135",
  str_detect(fullDirection$laserClockDir, "2:30 o'clock") & str_detect(fullDirection$Acft_Dir, "NW") ~ "30",
  str_detect(fullDirection$laserClockDir, "4:30 o'clock") & str_detect(fullDirection$Acft_Dir, "ESE") ~ "247.5",
  str_detect(fullDirection$laserClockDir, "4:30 o'clock") & str_detect(fullDirection$Acft_Dir, "SSE") ~ "292.5",
  str_detect(fullDirection$laserClockDir, "4:30 o'clock") & str_detect(fullDirection$Acft_Dir, "SE") ~ "270",
  str_detect(fullDirection$laserClockDir, "4:30 o'clock") & str_detect(fullDirection$Acft_Dir, "NE") ~ "180",
  str_detect(fullDirection$laserClockDir, "4:30 o'clock") & str_detect(fullDirection$Acft_Dir, "WNW") ~ "67.5",
  str_detect(fullDirection$laserClockDir, "4:30 o'clock") & str_detect(fullDirection$Acft_Dir, "W") ~ "45",
  str_detect(fullDirection$laserClockDir, "7:30 o'clock") & str_detect(fullDirection$Acft_Dir, "SE") ~ "0",
  TRUE ~ as.character(fullDirection$degreeLaserDir)))

#Converting clock to degrees
fullDirection$laserPilotDegree <- "NA"

fullDirection$laserPilotDegree <- case_when(
  str_detect(fullDirection$laserClockDir, "11 to 12 o'clock") ~ "345",
  str_detect(fullDirection$laserClockDir, "1 to 3 o'clock") ~ "60",
  str_detect(fullDirection$laserClockDir, "12 and 9 o'clock") ~ "345",  
  str_detect(fullDirection$laserClockDir, "2 to 3 o'clock") ~ "75",
  str_detect(fullDirection$laserClockDir, "2 to 6 o'clock") ~ "120",
  str_detect(fullDirection$laserClockDir, "10 o'clock") ~ "300",
  str_detect(fullDirection$laserClockDir, "11 o'clock") ~ "330",
  str_detect(fullDirection$laserClockDir, "12 o'clock") ~ "0",
  str_detect(fullDirection$laserClockDir, "1 o'clock") ~ "30",
  str_detect(fullDirection$laserClockDir, "2 o'clock") ~ "60",
  str_detect(fullDirection$laserClockDir, "3 o'clock") ~ "90", 
  str_detect(fullDirection$laserClockDir, "4 o'clock") ~ "120",  
  str_detect(fullDirection$laserClockDir, "5 o'clock") ~ "150", 
  str_detect(fullDirection$laserClockDir, "6 o'clock") ~ "180", 
  str_detect(fullDirection$laserClockDir, "7 o'clock") ~ "210",
  str_detect(fullDirection$laserClockDir, "8 o'clock") ~ "240",
  str_detect(fullDirection$laserClockDir, "9 o'clock") ~ "270",
  str_detect(fullDirection$laserClockDir, "11:30 o'clock") ~ "345", 
  str_detect(fullDirection$laserClockDir, "1:30 o'clock") ~ "45",
  str_detect(fullDirection$laserClockDir, "10:30 o'clock") ~ "315",
  str_detect(fullDirection$laserClockDir, "2:30 o'clock") ~ "75",
  str_detect(fullDirection$laserClockDir, "4:30 o'clock") ~ "135",
  str_detect(fullDirection$laserClockDir, "7:30 o'clock") ~ "225",
  str_detect(fullDirection$laserClockDir, "9:30 o'clock") ~ "285",  
  TRUE ~ as.character(fullDirection$laserPilotDegree))

write.csv(fullDirection,"C:/laser_direction_degree.csv", row.names = FALSE)
