#install.packages("tidyverse")
library(dplyr)
library(stringr)

#creates a new column for flight status: on ground, ascent, descent, and orbiting
#future steps would be to add: at altitude

#update path to data file
acftStatus <- read.csv("C:/laser_current.csv", header = TRUE)

acftStatus$flightStatus <- "na"

acftStatus$flightStatus <- case_when(
  str_detect(acftStatus$remarks, "taxiing") ~ "on ground",  
  str_detect(acftStatus$remarks, "taxing") ~ "on ground",  
  str_detect(acftStatus$remarks, "parked at Gate") ~ "on ground",  
  str_detect(acftStatus$remarks, "parked at gate") ~ "on ground",  
  str_detect(acftStatus$remarks, "parked atgate") ~ "on ground",  
  str_detect(acftStatus$remarks, "take off roll") ~ "on ground",  
  str_detect(acftStatus$remarks, "on departure roll") ~ "on ground",  
  str_detect(acftStatus$remarks, "on takeoff roll") ~ "on ground",  
  str_detect(acftStatus$remarks, "on the twy") ~ "on ground",  
  str_detect(acftStatus$remarks, "taxiway") ~ "on ground",  
  str_detect(acftStatus$remarks, "on departure from runway") ~ "on ground",  
  str_detect(acftStatus$remarks, "departure rotation") ~ "on ground",  
  str_detect(acftStatus$remarks, "on departure RWY") ~ "on ground",  
  str_detect(acftStatus$remarks, "pushed from gate") ~ "on ground",  
  str_detect(acftStatus$remarks, "on ramp") ~ "on ground",  
  str_detect(acftStatus$remarks, "after arrival") ~ "on ground",  
  str_detect(acftStatus$remarks, "awaiting departure") ~ "on ground",  
  str_detect(acftStatus$remarks, "on the landing pad") ~ "on ground",  
  str_detect(acftStatus$remarks, "on the helipad") ~ "on ground",  
  str_detect(acftStatus$remarks, "on the run-up area") ~ "on ground",  
  str_detect(acftStatus$remarks, "while landing") ~ "descent",  
  str_detect(acftStatus$remarks, "descent") ~ "descent",  
  str_detect(acftStatus$remarks, "whileon final") ~ "descent",  
  str_detect(acftStatus$remarks, "Acft landing") ~ "descent",  
  str_detect(acftStatus$remarks, "final to Runway") ~ "descent",  
  str_detect(acftStatus$remarks, "final to RWY") ~ "descent",  
  str_detect(acftStatus$remarks, "final toRwy") ~ "descent",  
  str_detect(acftStatus$remarks, "final toRWY") ~ "descent",  
  str_detect(acftStatus$remarks, "finalto RWY") ~ "descent",  
  str_detect(acftStatus$remarks, "finaltoRWY") ~ "descent",  
  str_detect(acftStatus$remarks, "final approach") ~ "descent",  
  str_detect(acftStatus$remarks, "final for RWY") ~ "descent",  
  str_detect(acftStatus$remarks, "final for Runway") ~ "descent",  
  str_detect(acftStatus$remarks, "final forRWY") ~ "descent",  
  str_detect(acftStatus$remarks, "FinalRWY") ~ "descent",  
  str_detect(acftStatus$remarks, "final RWY") ~ "descent",  
  str_detect(acftStatus$remarks, "finalfor Rwy") ~ "descent",  
  str_detect(acftStatus$remarks, "finial RWY") ~ "descent",  
  str_detect(acftStatus$remarks, "ON APPROACH") ~ "descent",  
  str_detect(acftStatus$remarks, "finalapproach") ~ "descent",  
  str_detect(acftStatus$remarks, "approach to runway") ~ "descent",  
  str_detect(acftStatus$remarks, "approach torunway") ~ "descent",  
  str_detect(acftStatus$remarks, "approach for runway") ~ "descent",  
  str_detect(acftStatus$remarks, "descending") ~ "descent",  
  str_detect(acftStatus$remarks, "Rwy 15 ILS final") ~ "descent",  
  str_detect(acftStatus$remarks, "right base for the runway") ~ "descent",  
  str_detect(acftStatus$remarks, "base leg") ~ "descent",  
  str_detect(acftStatus$remarks, "Base leg") ~ "descent",  
  str_detect(acftStatus$remarks, "base to final") ~ "descent",  
  str_detect(acftStatus$remarks, "base to runway") ~ "descent",  
  str_detect(acftStatus$remarks, "base to the runway") ~ "descent",  
  str_detect(acftStatus$remarks, "base for runway") ~ "descent",  
  str_detect(acftStatus$remarks, "base turn") ~ "descent",  
  str_detect(acftStatus$remarks, "base runway") ~ "descent",  
  str_detect(acftStatus$remarks, "base for RWY") ~ "descent",  
  str_detect(acftStatus$remarks, "base to RWY") ~ "descent",  
  str_detect(acftStatus$remarks, "base RY") ~ "descent",  
  str_detect(acftStatus$remarks, "base for RY") ~ "descent",  
  str_detect(acftStatus$remarks, "baseleg") ~ "descent",  
  str_detect(acftStatus$remarks, "LB Runway") ~ "descent",  
  str_detect(acftStatus$remarks, "downwind") ~ "descent",  
  str_detect(acftStatus$remarks, "Downwind") ~ "descent",  
  str_detect(acftStatus$remarks, "down wind") ~ "descent",  
  str_detect(acftStatus$remarks, "finalforRWY") ~ "descent",  
  str_detect(acftStatus$remarks, "final for rwy") ~ "descent",  
  str_detect(acftStatus$remarks, "FINAL for RWY") ~ "descent",  
  str_detect(acftStatus$remarks, "final to Rwy") ~ "descent",  
  str_detect(acftStatus$remarks, "final LAX RWY") ~ "descent",  
  str_detect(acftStatus$remarks, "final to DAL RWY") ~ "descent",  
  str_detect(acftStatus$remarks, "final Ry") ~ "descent",  
  str_detect(acftStatus$remarks, "final RY") ~ "descent",  
  str_detect(acftStatus$remarks, "finalto RY") ~ "descent",  
  str_detect(acftStatus$remarks, "final for RY") ~ "descent",  
  str_detect(acftStatus$remarks, "final to RY") ~ "descent",  
  str_detect(acftStatus$remarks, "final on RY") ~ "descent",  
  str_detect(acftStatus$remarks, "final toRY") ~ "descent",  
  str_detect(acftStatus$remarks, "finalRy") ~ "descent",  
  str_detect(acftStatus$remarks, "finalRY") ~ "descent",  
  str_detect(acftStatus$remarks, "for final") ~ "descent",  
  str_detect(acftStatus$remarks, "final for Ry") ~ "descent",  
  str_detect(acftStatus$remarks, "finalforRY") ~ "descent",  
  str_detect(acftStatus$remarks, "final for runway") ~ "descent",  
  str_detect(acftStatus$remarks, "final runway") ~ "descent",  
  str_detect(acftStatus$remarks, "FINAL RUNWAY") ~ "descent",  
  str_detect(acftStatus$remarks, "final to runway") ~ "descent",  
  str_detect(acftStatus$remarks, "FINAL APCH") ~ "descent",  
  str_detect(acftStatus$remarks, "mile final") ~ "descent",  
  str_detect(acftStatus$remarks, "milefinal") ~ "descent",  
  str_detect(acftStatus$remarks, "miles final") ~ "descent",  
  str_detect(acftStatus$remarks, "on final") ~ "descent",  
  str_detect(acftStatus$remarks, "onfinal") ~ "descent",  
  str_detect(acftStatus$remarks, "on Final") ~ "descent",  
  str_detect(acftStatus$remarks, "1N final") ~ "descent",  
  str_detect(acftStatus$remarks, "NM final") ~ "descent",  
  str_detect(acftStatus$remarks, "NM of final") ~ "descent",  
  str_detect(acftStatus$remarks, "NM to RWY") ~ "descent",  
  str_detect(acftStatus$remarks, "NM of RWY") ~ "descent",  
  str_detect(acftStatus$remarks, "NMfinal") ~ "descent",  
  str_detect(acftStatus$remarks, "NMFinal") ~ "descent",  
  str_detect(acftStatus$remarks, "NM Final") ~ "descent",  
  str_detect(acftStatus$remarks, "nm final") ~ "descent",  
  str_detect(acftStatus$remarks, "Nm final") ~ "descent",  
  str_detect(acftStatus$remarks, "short final") ~ "descent",  
  str_detect(acftStatus$remarks, "Short final") ~ "descent",  
  str_detect(acftStatus$remarks, "shortfinal") ~ "descent",  
  str_detect(acftStatus$remarks, "finalRWY") ~ "descent",  
  str_detect(acftStatus$remarks, "final torunway") ~ "descent",  
  str_detect(acftStatus$remarks, "fianl to RWY") ~ "descent",  
  str_detect(acftStatus$remarks, "NW of final") ~ "descent",  
  str_detect(acftStatus$remarks, "RY28L final") ~ "descent",  
  str_detect(acftStatus$remarks, "RY28R final") ~ "descent",  
  str_detect(acftStatus$remarks, "turning final") ~ "descent",  
  str_detect(acftStatus$remarks, "turning onto final") ~ "descent",  
  str_detect(acftStatus$remarks, "mi final") ~ "descent",  
  str_detect(acftStatus$remarks, "while onfinal") ~ "descent",  
  str_detect(acftStatus$remarks, "on 2final") ~ "descent",  
  str_detect(acftStatus$remarks, "on base final") ~ "descent",  
  str_detect(acftStatus$remarks, "Mile final") ~ "descent",  
  str_detect(acftStatus$remarks, "RY14 final") ~ "descent",  
  str_detect(acftStatus$remarks, "FAP") ~ "descent",  
  str_detect(acftStatus$remarks, "approach") ~ "descent",  
  str_detect(acftStatus$remarks, "Approach") ~ "descent",  
  str_detect(acftStatus$remarks, "landing runway") ~ "descent",  
  str_detect(acftStatus$remarks, "inbound to Runway") ~ "descent",  
  str_detect(acftStatus$remarks, "in-bound") ~ "descent",  
  str_detect(acftStatus$remarks, "arriving") ~ "descent",  
  str_detect(acftStatus$remarks, "arrival") ~ "descent",  
  str_detect(acftStatus$remarks, "Arrival") ~ "descent",  
  str_detect(acftStatus$remarks, "during landing") ~ "descent",  
  str_detect(acftStatus$remarks, "whilelanding") ~ "descent",  
  str_detect(acftStatus$remarks, "pattern") ~ "descent",  
  str_detect(acftStatus$remarks, "take off") ~ "ascent",  
  str_detect(acftStatus$remarks, "after departing") ~ "ascent",  
  str_detect(acftStatus$remarks, "climb") ~ "ascent",  
  str_detect(acftStatus$remarks, "departure phase") ~ "ascent",  
  str_detect(acftStatus$remarks, "crosswind") ~ "ascent",  
  str_detect(acftStatus$remarks, "departing") ~ "ascent",  
  str_detect(acftStatus$remarks, "depature end of runway") ~ "ascent",  
  str_detect(acftStatus$remarks, "departure end") ~ "ascent",  
  str_detect(acftStatus$remarks, "after departure") ~ "ascent",  
  str_detect(acftStatus$remarks, "upon departure") ~ "ascent",  
  str_detect(acftStatus$remarks, "departureroute") ~ "ascent",  
  str_detect(acftStatus$remarks, "departure Runway") ~ "ascent",  
  str_detect(acftStatus$remarks, "on departure") ~ "ascent",  
  str_detect(acftStatus$remarks, "On departure") ~ "ascent",  
  str_detect(acftStatus$remarks, "during departure") ~ "ascent",  
  str_detect(acftStatus$remarks, "NM off departure") ~ "ascent",  
  str_detect(acftStatus$remarks, "departures") ~ "ascent",  
  str_detect(acftStatus$remarks, "departure heading") ~ "ascent",  
  str_detect(acftStatus$remarks, "Departure heading") ~ "ascent",  
  str_detect(acftStatus$remarks, "Multiple departures") ~ "ascent",  
  str_detect(acftStatus$remarks, "orbiting") ~ "orbiting",  
  TRUE ~ as.character(acftStatus$flightStatus))



write.csv(acftStatus,"C:/laser_flightStatusv2.csv", row.names = FALSE)
